#pragma once

#include "DLLExport.h"

#define TO_STRING(x) #x

#define DUMMY_EXPORT(FUNCTION_NAME,RETURN_TYPE,...)\
typedef RETURN_TYPE(*FUNCTION_NAME##_Type)(__VA_ARGS__);\
FUNCTION_NAME##_Type Real##FUNCTION_NAME = NULL;\
DLLEXPORT RETURN_TYPE FUNCTION_NAME(__VA_ARGS__)

#define DUMMY_IMPORT(MODULE,FUNCTION_NAME)\
Real##FUNCTION_NAME = (FUNCTION_NAME##_Type) GetProcAddress(MODULE, #FUNCTION_NAME)

#define DUMMY_EXPORT_AW(FUNCTION_NAME,RETURN_TYPE,...)\
typedef RETURN_TYPE(*FUNCTION_NAME##_Type)(__VA_ARGS__);\
FUNCTION_NAME##_Type Real##FUNCTION_NAME##A = NULL;\
FUNCTION_NAME##_Type Real##FUNCTION_NAME##W = NULL;\
DLLEXPORT RETURN_TYPE FUNCTION_NAME##A(__VA_ARGS__);\
DLLEXPORT RETURN_TYPE FUNCTION_NAME##W(__VA_ARGS__)

#define DUMMY_IMPORT_AW(MODULE,FUNCTION_NAME)\
Real##FUNCTION_NAME##A = (FUNCTION_NAME##_Type) GetProcAddress(MODULE, TO_STRING(FUNCTION_NAME##A));\
Real##FUNCTION_NAME##W = (FUNCTION_NAME##_Type) GetProcAddress(MODULE, TO_STRING(FUNCTION_NAME##W))