#pragma once

#define DUMMY_EXPORT(FUNCTION_NAME,RETURN_TYPE,...)\
typedef RETURN_TYPE(*FUNCTION_NAME##_Type)(__VA_ARGS__);\
FUNCTION_NAME##_Type Real##FUNCTION_NAME = NULL;\
DLLEXPORT RETURN_TYPE FUNCTION_NAME(__VA_ARGS__)

#define DUMMY_IMPORT(MODULE,FUNCTION_NAME)\
Real##FUNCTION_NAME = (FUNCTION_NAME##_Type) GetProcAddress(MODULE, #FUNCTION_NAME)