#pragma once

#include "DLLExport.h"

#define TO_STRING(x) #x

// 声明一个函数指针
#define FUN_POINTER(FUNCTION_NAME,RETURN_TYPE,...)\
typedef RETURN_TYPE(*FUNCTION_NAME##_Type)(__VA_ARGS__);\
FUNCTION_NAME##_Type Real##FUNCTION_NAME = NULL

/*
* 这里先手动加上WINAPI 也就是调用约定 stdcall
* 否则在Win32（x86）程序中会因为调用约定不一致导致出现Run-Time Check Failure #0 ESP错误
* x64 程序中调用约定基本已经统一，不会出现此类错误。
*/
// 声明共享同一函数指针类型的两个函数
#define FUN_POINTER_SHARE_TWO(FUNCTION_NAME,RETURN_TYPE,PARAMS,SUFFIX1,SUFFIX2)\
typedef RETURN_TYPE(WINAPI *FUNCTION_NAME##_Type)PARAMS;\
FUNCTION_NAME##_Type Real##FUNCTION_NAME##SUFFIX1 = NULL;\
FUNCTION_NAME##_Type Real##FUNCTION_NAME##SUFFIX2 = NULL

// 声明一个Windows中的系统函数，不可以直接导出，需要借助DEF文件进行导出
#define DUMMY_WINFUN_EXPORT(FUNCTION_NAME,RETURN_TYPE,...)\
FUN_POINTER(FUNCTION_NAME, RETURN_TYPE, __VA_ARGS__); \
RETURN_TYPE FUNCTION_NAME(__VA_ARGS__)

// 声明一个导出函数
#define DUMMY_EXPORT(FUNCTION_NAME,RETURN_TYPE,...)\
FUN_POINTER(FUNCTION_NAME,RETURN_TYPE,__VA_ARGS__);\
DLLEXPORT RETURN_TYPE FUNCTION_NAME(__VA_ARGS__)

// 导入函数指针
#define FUN_IMPORT(MODULE,FUNCTION_NAME,EXPORT_NAME)\
Real##FUNCTION_NAME = (FUNCTION_NAME##_Type) GetProcAddress(MODULE, #EXPORT_NAME)

#define DUMMY_IMPORT(MODULE,FUNCTION_NAME)\
FUN_IMPORT(MODULE,FUNCTION_NAME,FUNCTION_NAME)

#define CHECK_IMPORT_STATE(FUNCTION_NAME)\
if(Real##FUNCTION_NAME){printf("%s on %p\n",TO_STRING(Real##FUNCTION_NAME),Real##FUNCTION_NAME);}else{printf("%s is null.\n",TO_STRING(Real##FUNCTION_NAME));}


#define DAFULT_FUNCTION(FUNCTION_NAME,RETURN_TYPE,PARAMS,ARGS,PRE,POST,RETURN_DEFAULT)\
RETURN_TYPE FUNCTION_NAME PARAMS{\
PRE\
 if(Real##FUNCTION_NAME){return Real##FUNCTION_NAME ARGS;}\
POST\
 RETURN_DEFAULT\
}\

#define DUMMY_EXPORT_AW(FUNCTION_NAME,RETURN_TYPE,...)\
typedef RETURN_TYPE(*FUNCTION_NAME##_Type)(__VA_ARGS__);\
FUNCTION_NAME##_Type Real##FUNCTION_NAME##A = NULL;\
FUNCTION_NAME##_Type Real##FUNCTION_NAME##W = NULL;\
RETURN_TYPE FUNCTION_NAME##A(__VA_ARGS__);\
RETURN_TYPE FUNCTION_NAME##W(__VA_ARGS__)

#define DUMMY_IMPORT_AW(MODULE,FUNCTION_NAME)\
Real##FUNCTION_NAME##A = (FUNCTION_NAME##_Type) GetProcAddress(MODULE, TO_STRING(FUNCTION_NAME##A));\
Real##FUNCTION_NAME##W = (FUNCTION_NAME##_Type) GetProcAddress(MODULE, TO_STRING(FUNCTION_NAME##W))

#define CHECK_IMPORT_STATE_AW(FUNCTION_NAME)\
CHECK_IMPORT_STATE(FUNCTION_NAME##A)\
CHECK_IMPORT_STATE(FUNCTION_NAME##W)

#define DAFULT_FUNCTION_SHARE_TWO(FUNCTION_NAME,RETURN_TYPE,PARAMS,ARGS,PRE,POST,RETURN_DEFAULT,SUFFIX1,SUFFIX2)\
DAFULT_FUNCTION(FUNCTION_NAME##SUFFIX1, RETURN_TYPE, PARAMS, ARGS, PRE, POST, RETURN_DEFAULT)\
DAFULT_FUNCTION(FUNCTION_NAME##SUFFIX2, RETURN_TYPE, PARAMS, ARGS, PRE, POST, RETURN_DEFAULT)